### PR TITLE
Raising missing events #1741

### LINKED ISSUE #1741: Inconsistency of raising ExecutionStartingRequest event for grpc plugins if running specs in parallel
I'm developer of plugin for gauge with grpc support.

When we execute specs using `gauge run` command, plugin gets following execution starting 2 events (json serialized):
```
{"CurrentExecutionInfo":null,"SuiteResult":null,"Stream":0}
{"CurrentExecutionInfo":null,"SuiteResult":{"SpecResults":[],"PreHookFailure":null,"PostHookFailure":null,"Failed":false,"SpecsFailedCount":0,"ExecutionTime":0,"SuccessRate":0,"Environment":"default","Tags":"","ProjectName":"sample-gauge-project-master","Timestamp":"Sep 4, 2020 at 7:48pm","SpecsSkippedCount":0,"PreHookMessages":[],"PostHookMessages":[],"PreHookMessage":[],"PostHookMessage":[],"PreHookScreenshots":[],"PostHookScreenshots":[],"Chunked":false,"ChunkSize":0,"PreHookScreenshotFiles":[],"PostHookScreenshotFiles":[]},"Stream":0}
```

Plugin expects that 2 events are raised. It's true for gauge v1.0.7 and v1.1.1.

But if we run specs in parallel `gauge run -p` then only 1 event is raised in gauge v1.1.1:
```
{"CurrentExecutionInfo":{"CurrentSpec":null,"CurrentScenario":null,"CurrentStep":null,"Stacktrace":"","ProjectName":"","ExecutionArgs":[],"NumberOfExecutionStreams":0,"RunnerId":0},"SuiteResult":null,"Stream":1}
```

Note: With gauge v1.0.7 parallel execution fires 2 events as expected.

### PR DESCRIPTION
**Pull request by BugDiver**
fixes #1741

### CODE REVIEW

File: execution/parallelGrpcExecution_test.go [hunk 1]
```diff
@@ -19,16 +19,20 @@ import (
...
+	var recievedMesseges []*gauge_messages.Message
 	runner1 := &fakeGrpcRunner{messageCount: make(map[gauge_messages.Message_MessageType]int)}
 	runner2 := &fakeGrpcRunner{messageCount: make(map[gauge_messages.Message_MessageType]int)}
 	e := parallelExecution{
 		numberOfExecutionStreams: 5,
 		specCollection:           gauge.NewSpecCollection(specs, false),
 		runners:                  []runner.Runner{runner1, runner2},
-		pluginHandler:            &mockPluginHandler{NotifyPluginsfunc: func(m *gauge_messages.Message) {}},
+		pluginHandler: &mockPluginHandler{NotifyPluginsfunc: func(m *gauge_messages.Message) {
+			recievedMesseges = append(recievedMesseges, m)
```
Comment (sriv) [inline execution/parallelGrpcExecution_test.go:30]: typo in variable name

File: execution/parallelGrpcExecution_test.go [hunk 2]
```diff
@@ -19,16 +19,20 @@ import (
 
 func TestSuiteHooksAreExecutedOncePerRun(t *testing.T) {
 	specs := createSpecsList(6)
+	var recievedMesseges []*gauge_messages.Message
```
Comment (sriv) [inline execution/parallelGrpcExecution_test.go:22]: typo in variable name

**Review by sriv — CHANGES_REQUESTED** [review]

**Review by sriv — APPROVED** [review]
